# Generated by Django 3.2.19 on 2023-07-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user_profile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user_user',
        ),
    ]
