# Generated by Django 3.2.20 on 2023-07-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230722_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gamification_sub_type',
            field=models.CharField(blank=True, choices=[(0, 'Philanthropist'), (1, 'Socialiser'), (2, 'Free Spirit'), (3, 'Achiever'), (4, 'Disruptor'), (5, 'Player')], max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='gamification_type',
            field=models.CharField(blank=True, choices=[(0, 'Philanthropist'), (1, 'Socialiser'), (2, 'Free Spirit'), (3, 'Achiever'), (4, 'Disruptor'), (5, 'Player')], max_length=255),
        ),
    ]
