# Generated by Django 3.2.20 on 2023-07-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_profile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gamification_sub_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Philanthropist'), (1, 'Socialiser'), (2, 'Free Spirit'), (3, 'Achiever'), (4, 'Disruptor'), (5, 'Player')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gamification_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Philanthropist'), (1, 'Socialiser'), (2, 'Free Spirit'), (3, 'Achiever'), (4, 'Disruptor'), (5, 'Player')], null=True),
        ),
    ]
