# Generated by Django 3.2.20 on 2023-07-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230723_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='body_fat',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
