# Generated by Django 3.2.23 on 2024-03-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='gamification_sub_type',
            new_name='HEXAD_12_sub_type',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='gamification_type',
            new_name='HEXAD_12_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='motivation_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Non-Regulation'), (1, 'External Regulation'), (2, 'Introjected Regulation'), (3, 'Identified Regulation'), (4, 'Integrated Regulation'), (5, 'Intrinsic Motivation')], null=True),
        ),
    ]
