# Generated by Django 3.2.23 on 2024-03-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20240308_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='HEXAD_12_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
