# Generated by Django 3.2.23 on 2024-03-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20240319_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='HEXAD_12_sub_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='HEXAD_12_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='motivation_type',
        ),
    ]
