# Generated by Django 3.2.23 on 2024-03-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_profile_current_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
    ]
