# Generated by Django 3.2.23 on 2024-04-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_profile_current_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_streak',
            field=models.IntegerField(default=1),
        ),
    ]
