# Generated by Django 3.2.23 on 2024-04-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20240429_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goal_progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
