# Generated by Django 3.2.19 on 2023-07-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('response_time', models.FloatField(default=0)),
                ('message', models.CharField(max_length=255)),
                ('status_code', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'log_user',
                'ordering': ['-id'],
            },
        ),
    ]
