# Generated by Django 3.2.19 on 2023-07-08 17:39

import api.macronutrient.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macronutrient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='macronutrient',
            managers=[
                ('objects', api.macronutrient.managers.MacronutrientManager()),
            ],
        ),
    ]
