version: "3.8"

services:
  sustain-dev-db:
    container_name: sustain-dev-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - sustain-dev-data:/var/lib/postgresql/data/
    build:
      context: ./
      dockerfile: db.Dockerfile

  sustain-dev-api:
    container_name: sustain-dev-api
    env_file:
      - .env.dev
    build:
      context: ./
      dockerfile: api.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:  
      - .:/code
      - media:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - sustain-dev-db

volumes:
  media:
  sustain-dev-data: