# Generated by Django 3.2.23 on 2024-04-30 15:19

import api.game_element_quiz.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.TextField()),
                ('option_one', models.CharField(default='', max_length=255)),
                ('option_two', models.CharField(default='', max_length=255)),
                ('option_three', models.CharField(default='', max_length=255)),
                ('option_four', models.CharField(default='', max_length=255)),
                ('correct_answer', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'game_element_quiz',
                'ordering': ['id'],
            },
            managers=[
                ('objects', api.game_element_quiz.managers.GameQuizManager()),
            ],
        ),
    ]
