# Generated by Django 3.2.23 on 2024-05-02 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_element', '0002_alter_gameelement_table'),
        ('user', '0028_remove_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('game_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_element.gameelement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'db_table': 'recommender_ranking',
                'unique_together': {('user', 'game_element')},
            },
        ),
    ]
