# Generated by Django 3.2.23 on 2024-05-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rating',
            table='recommender_rating',
        ),
    ]
