# Generated by Django 3.2.23 on 2024-05-04 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_rating', '0003_rating_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='created_at',
            new_name='added_at',
        ),
    ]
