# Generated by Django 3.2.19 on 2023-07-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0003_auto_20230708_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
