# Generated by Django 3.2.19 on 2023-07-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motivation', '0002_add_data'),
        ('user', '0002_auto_20230708_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('motivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motivation.motivation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'db_table': 'user_motivation_profile',
            },
        ),
    ]
