# Generated by Django 3.2.19 on 2023-07-19 14:04

import api.gamification_question.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamification_type', '0002_add_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.TextField()),
                ('gamification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification_type.gamificationtype')),
            ],
            options={
                'db_table': 'gamification_question',
                'ordering': ['id'],
            },
            managers=[
                ('objects', api.gamification_question.managers.GamificationQuestionManager()),
            ],
        ),
    ]
