# Generated by Django 3.2.19 on 2023-07-21 09:44

import api.motivation_question.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motivation', '0002_add_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('question', models.CharField(max_length=255, unique=True)),
                ('motivation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motivation.motivation')),
            ],
            options={
                'db_table': 'motivation_question',
                'ordering': ['id'],
            },
            managers=[
                ('objects', api.motivation_question.managers.MotivationQuestionManager()),
            ],
        ),
    ]
