# Generated by Django 3.2.19 on 2023-07-05 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('macronutrient', '0001_initial'),
        ('food', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodintake',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food',
            name='macronutrients',
            field=models.ManyToManyField(through='food.MacronutrientFood', to='macronutrient.Macronutrient'),
        ),
        migrations.AlterUniqueTogether(
            name='macronutrientfood',
            unique_together={('food', 'macronutrient')},
        ),
        migrations.AlterUniqueTogether(
            name='foodintake',
            unique_together={('user', 'food', 'date')},
        ),
    ]
