# Generated by Django 3.2.19 on 2023-07-08 17:33

import api.food.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='food',
            managers=[
                ('objects', api.food.managers.FoodManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='macronutrientfood',
            managers=[
                ('objects', api.food.managers.MacronutrientFoodManager()),
            ],
        ),
        migrations.AlterModelTable(
            name='foodintake',
            table='food_foodintake',
        ),
    ]
