# Generated by Django 3.2.23 on 2024-05-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recommendersystem',
            managers=[
            ],
        ),
    ]
