# Generated by Django 3.2.23 on 2024-05-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendersystem',
            old_name='recommended_items',
            new_name='game_element',
        ),
    ]
