# Generated by Django 3.2.23 on 2024-05-01 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_element', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gameelement',
            table='game_element',
        ),
    ]
