# Generated by Django 3.2.23 on 2024-05-01 14:37

import api.gamification_pointsystem.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationPointsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('element_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('point', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gamification_pointsystem',
                'ordering': ['id'],
            },
            managers=[
                ('objects', api.gamification_pointsystem.managers.GamificationPointsystemManager()),
            ],
        ),
    ]
